### ISSUE TITLE
Neat theme structure

### ISSUE THREAD

**Issue by szepeviktor** [melchoyce/aventurine#35]
![kép](https://user-images.githubusercontent.com/952007/96082353-5d2f8280-0ebb-11eb-9797-a48950c4eced.png)

Are you interested in de-cluttering root? 🧹 
https://github.com/szepeviktor/aventurine/tree/neat-structure

**Comment by szepeviktor** [comment]
WordPress core has built-in support for subfolders!

**Comment by ryelle** [comment]
Thanks for the suggestion, but we're happy with the structure as it is now.
